<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TeacherConsole</RootNamespace>
    <AssemblyName>TeacherConsole</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClassroomNetGuard.Shared\ClassroomNetGuard.Shared.csproj" />
  </ItemGroup>
</Project>
